name: Download Kaggle Output

on: [push]

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Kaggle API
      run: pip install kaggle

    - name: Set up Kaggle API credentials
      run: |
        mkdir -p ~/.kaggle
        echo "$KAGGLE_JSON" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json
      env:
        KAGGLE_JSON: ${{ secrets.KAGGLE_JSON }}

    - name: Download Kaggle Output
      run: python download_kaggle_output.py

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

    - name: Commit and Push Changes
      run: |
        git add output/
        git commit -m "Add Kaggle output"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
