name: Download Kaggle Files

on:
  push:
    branches:
      - main

jobs:
  download-kaggle-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Kaggle API
      run: pip install kaggle

    - name: Configure Kaggle credentials
      run: |
        mkdir -p ~/.kaggle
        echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json

    - name: Download Kaggle dataset
      run: kaggle datasets download -d revanthonteddu/treasury-bills-data -p data --unzip

    - name: List downloaded files
      run: ls -la data
